name: avici
channels:
- conda-forge
- defaults
dependencies:
- conda
- python=3.10.6
- jaxlib=0.3.14 # jax installed via pip (Apple silicon compatibility)
- tensorflow=2.9.1
- pip
- pip:
  - -r ./requirements.txt
  - -e . # this repo
