---
data:
  - n_observations_obs: null
    n_observations_int: null

    graph:
      - __class__: ScaleFreeTranspose
        edges_per_var: [ 2 ]
        power: [ 0.5, 1.5 ]

      - __class__: WattsStrogatz
        dim: [ 2, 3 ]
        nei: [ 1 ]
        p: [ 0.3 ]

      - __class__: SBM
        edges_per_var: [ 2 ]
        n_blocks: [ 5, 10 ]
        damp: [ 0.1 ]

      - __class__: GRG
        radius: [ 0.1 ]

    mechanism:
      - __class__: RFFAdditive

        length_scale:
          - __class__: Uniform
            low: 7.0
            high: 10.0

        output_scale:
          - __class__: Uniform
            low: 10.0
            high: 20.0

        bias:
          - __class__: Uniform
            low: -3.0
            high: 3.0

        noise:
          - __class__: Cauchy

        noise_scale_heteroscedastic:
          - rff:
            length_scale: 10.0
            output_scale: 2.0

        n_interv_vars: -1
        interv_dist:
          - __class__: SignedUniform
            low:  1.0
            high: 5.0